matrix:
    include:
        - os: linux
          sudo: required
          dist: trusty
          language: c
        - os: osx
          language: c
          osx_image: xcode7.3

cache:
  ccache: true
  directories:
  - dependencies/linux
  - dependencies/osx

before_install: date +%s > ${HOME}/start_time

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./reproducible_build_osx.sh -t -d; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./reproducible_build.sh -t; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./reproducible_build_osx.sh -t -l; fi
